- changelog.md
- composer.json
- composer.lock
- wp-content/plugins/core/src/Service_Providers/Twig_Service_Provider.php
- wp-content/plugins/core/src/Twig/Extension.php
- wp-content/plugins/core/src/Twig/Twig_Cache.php
- wp-content/plugins/core/src/Twig/Twig_Template.php
Reverts moderntribe/square-one#340
> Revert "Feature/upgrade twig components"

- changelog.md
- wp-content/plugins/core/src/Theme/Page_Title.php
Small readability and code quality tweak.
> Remove unnecessary Else Ifs in PageTitle class

- composer.lock
Was running into cannot find `\Tribe\Gutenpanels\Plugin` before regenerating the lock
> Fix Tribe\Gutenpanels not being found

- changelog.md
- composer.lock
Fixes https://github.com/moderntribe/square-one/issues/407
> Fix broken merged composer.lock file

- composer.json
- composer.lock
- wp-content/plugins/core/src/Admin/Admin_Subscriber.php
- wp-content/plugins/core/src/Blocks/Blocks_Subscriber.php
- wp-content/plugins/core/src/CLI/CLI_Subscriber.php
- wp-content/plugins/core/src/Cache/Cache_Subscriber.php
- wp-content/plugins/core/src/Content/Content_Subscriber.php
- wp-content/plugins/core/src/Core.php
- wp-content/plugins/core/src/Development/Whoops_Subscriber.php
- wp-content/plugins/core/src/Nav_Menus/Nav_Menus_Subscriber.php
- wp-content/plugins/core/src/Object_Meta/Object_Meta_Subscriber.php
- wp-content/plugins/core/src/P2P/P2P_Subscriber.php
- wp-content/plugins/core/src/Panels/Panels_Subscriber.php
- wp-content/plugins/core/src/Post_Types/Post_Type_Subscriber.php
- wp-content/plugins/core/src/Settings/Settings_Subscriber.php
- wp-content/plugins/core/src/Shortcodes/Shortcodes_Subscriber.php
- wp-content/plugins/core/src/Taxonomies/Taxonomy_Subscriber.php
- wp-content/plugins/core/src/Templates/Templates_Subscriber.php
- wp-content/plugins/core/src/Theme/Theme_Subscriber.php
- wp-content/plugins/core/src/Theme_Customizer/Theme_Customizer_Subscriber.php
https://github.com/moderntribe/tribe-libs/pull/37 changes the `Subscriber_Interface` and adds an `Abstract_Subscriber`. This implements the change across all subscribers in the core plugin.
> implement the change to the subscriber interface from tribe-libs #37

- package.json
- wp-content/plugins/core/src/Theme/Config/Web_Fonts.php
- wp-content/plugins/core/src/Theme/Theme_Definer.php
- wp-content/plugins/core/src/Theme/Theme_Subscriber.php
- yarn.lock
Updates Sq1 to load web fonts via CSS rather than JS.
[SQONE-133]
[SQONE-133]: https://moderntribe.atlassian.net/browse/SQONE-133
> Feeture/sqone 133/load webfonts via css

- wp-content/themes/core/assets/css/src/theme/forms/_mixins.pcss
- wp-content/themes/core/assets/css/src/theme/forms/_variables.pcss
- wp-content/themes/core/assets/css/src/theme/forms/attributes.pcss
- wp-content/themes/core/assets/css/src/theme/forms/default.pcss
- wp-content/themes/core/assets/css/src/theme/forms/fieldset.pcss
- wp-content/themes/core/assets/css/src/theme/forms/file.pcss
- wp-content/themes/core/assets/css/src/theme/forms/label.pcss
- wp-content/themes/core/assets/css/src/theme/forms/legend.pcss
- wp-content/themes/core/assets/css/src/theme/forms/radio-checkbox.pcss
- wp-content/themes/core/assets/css/src/theme/forms/select.pcss
- wp-content/themes/core/components/page/page-kitchen-sink-forms/page-kitchen-sink-forms.twig
- wp-content/themes/core/integrations/chosen/css/_variables.pcss
- wp-content/themes/core/integrations/chosen/css/chosen.pcss
- wp-content/themes/core/integrations/gravity-forms/css/_variables.pcss
- wp-content/themes/core/integrations/gravity-forms/css/complex-layouts.pcss
- wp-content/themes/core/integrations/gravity-forms/css/controls/default.pcss
- wp-content/themes/core/integrations/gravity-forms/css/controls/file.pcss
- wp-content/themes/core/integrations/gravity-forms/css/controls/lists.pcss
- wp-content/themes/core/integrations/gravity-forms/css/controls/radio-checkbox.pcss
- wp-content/themes/core/integrations/gravity-forms/css/controls/textarea.pcss
- wp-content/themes/core/integrations/gravity-forms/css/controls/time-date.pcss
- wp-content/themes/core/integrations/gravity-forms/css/default.pcss
- wp-content/themes/core/integrations/gravity-forms/css/label.pcss
- wp-content/themes/core/integrations/gravity-forms/css/validation/error.pcss
- wp-content/themes/core/integrations/gravity-forms/css/validation/success.pcss
- wp-content/themes/core/integrations/jquery-datepicker/css/_variables.pcss
- wp-content/themes/core/integrations/jquery-datepicker/css/jquery-datepicker.pcss
- wp-content/themes/core/page-templates/page-kitchen-sink-forms.php
JIRA: https://moderntribe.atlassian.net/browse/SQONE-176
**WORK IN PROGRESS**
> Feeture/SQONE 176/forms

- wp-content/themes/core/assets/css/src/theme/layouts/_variables.pcss
> SQONE-182 bug fix for grid width.

- wp-content/themes/core/assets/css/src/theme/actions/_mixins.pcss
- wp-content/themes/core/assets/css/src/theme/media/alignment.pcss
- wp-content/themes/core/assets/css/src/theme/typography/quotes.pcss
- wp-content/themes/core/assets/css/src/theme/typography/themes.pcss
Couple small updates to the kitchen sink elements per design QA w/ Kyle.
[SQONE-418]
[SQONE-418]: https://moderntribe.atlassian.net/browse/SQONE-418
> Feeture/sqone 418/kitchen sink dqa

- dev/deploy/JenkinsfileManual
- dev/deploy/JenkinsfilePipeline
- package.json
- wp-content/themes/core/gulpfile.js
@nickpelton could you check this out? Just a few small tweaks. i think there may be some other parts that need some path adjustment, eg the ignore patterns below, but dont know best path there
> Patch deploy for build to theme

- .github/workflows/ci.yml
- .github/workflows/phpcs.yml
- composer.lock
- dev/docker/docker-compose.yml
- dev/docker/phpdocker/php-fpm/Dockerfile
Updates the PHP Dockerfile to use PHP 7.4
> update php docker image to 7.4

- wp-content/themes/core/assets/css/src/theme/layouts/_variables.pcss
- wp-content/themes/core/assets/css/src/theme/layouts/default.pcss
- wp-content/themes/core/assets/css/src/theme/typography/headings.pcss
- wp-content/themes/core/components/panels/media-text/css/media-text.pcss
Misc improvements to the Media & Text panel before moving on.
Note: we still need to suss out the block editor attributes & classes.
[SQONE-212]
[SQONE-212]: https://moderntribe.atlassian.net/browse/SQONE-212
> Feeture/sqone 212/panel media text improvements

- wp-content/plugins/core/src/Blocks/Types/Interstitial.php
- wp-content/plugins/core/src/Templates/Controllers/Block/Interstitial.php
- wp-content/themes/core/assets/css/src/admin/block-editor/blocks/tribe.pcss
- wp-content/themes/core/assets/css/src/admin/block-editor/editor.pcss
- wp-content/themes/core/components/panels/interstitial/Interstitial.php
Handles the public --> preview --> edit UI experience for the Interstitial panel.
Some commented & temp code here while we await some additional gutenpanels features.
[SQONE-224]
[SQONE-224]: https://moderntribe.atlassian.net/browse/SQONE-224
> Feeture/sqone 224/interstitial edit ui

- wp-content/plugins/core/src/Blocks/Types/Hero.php
- wp-content/plugins/core/src/Blocks/Types/Interstitial.php
- wp-content/plugins/core/src/Templates/Controllers/Block/Hero.php
- wp-content/plugins/core/src/Templates/Controllers/Block/Interstitial.php
- wp-content/themes/core/assets/css/src/admin/block-editor/blocks/tribe.pcss
- wp-content/themes/core/components/panels/hero/Hero.php
- wp-content/themes/core/components/panels/hero/css/hero.pcss
- wp-content/themes/core/components/panels/interstitial/css/interstitial.pcss
SQONE-215 Update Hero for Edit UI & layout standardize option naming
SQONE-224 Standardize layout option naming for Interstitial
[SQONE-215]
[SQONE-224]
[SQONE-215]: https://moderntribe.atlassian.net/browse/SQONE-215
[SQONE-224]: https://moderntribe.atlassian.net/browse/SQONE-224
> Updates to Hero & Interstitial for Edit UI & option naming

- composer.lock
I'm just pointing to the last gutenpanels commit that includes the post select/query
> Update gp to latest select ui commit

- wp-content/themes/core/assets/css/src/theme/forms/_mixins.pcss
- wp-content/themes/core/assets/css/src/theme/forms/radio-checkbox.pcss
- wp-content/themes/core/components/page/page-kitchen-sink-forms/page-kitchen-sink-forms.twig
QA fixes for forms sink
https://moderntribe.atlassian.net/browse/SQONE-176
> SQONE-176 QA fixes for forms sink

- composer.lock
I'm just pointing to the last gutenpanels commit that includes this PR https://github.com/moderntribe/square-one/pull/508
> Update GP to latest commit

- wp-content/plugins/core/src/Assets/Theme/Legacy_Check.php
- wp-content/plugins/core/src/Blocks/Blocks_Definer.php
- wp-content/plugins/core/src/Blocks/Types/Quote/Controller.php
- wp-content/plugins/core/src/Blocks/Types/Quote/Quote.php
- wp-content/plugins/core/src/Theme/Config/Image_Sizes.php
- wp-content/plugins/core/src/Theme/Config/Supports.php
- wp-content/themes/core/assets/css/src/theme/global/reset.pcss
- wp-content/themes/core/assets/css/src/theme/layouts/_variables.pcss
- wp-content/themes/core/assets/css/src/theme/typography/_mixins.pcss
- wp-content/themes/core/assets/css/src/theme/typography/quotes.pcss
- wp-content/themes/core/components/blocks/quote/Quote.php
- wp-content/themes/core/components/blocks/quote/css/quote.pcss
- wp-content/themes/core/components/blocks/quote/index.pcss
- wp-content/themes/core/components/blocks/quote/quote.twig
- wp-content/themes/core/components/document/document.twig
- wp-content/themes/core/components/quote/Quote.php
- wp-content/themes/core/components/quote/quote.twig
Builds out the FE for the Quote Block. Updates the Quote component to be more flexible.
Based from #521 as this inherits the Panel --> Block renaming.
- [SQONE-257]
[SQONE-257]: https://moderntribe.atlassian.net/browse/SQONE-257
> Feeture/sqone 257/quote block

- wp-content/plugins/core/src/Blocks/Blocks_Definer.php
- wp-content/plugins/core/src/Blocks/Types/Lead_Form/Lead_Form.php
- wp-content/themes/core/assets/img/admin/blocks/lead-form/center.svg
- wp-content/themes/core/assets/img/admin/blocks/lead-form/full.svg
- wp-content/themes/core/assets/img/admin/blocks/lead-form/grid.svg
- wp-content/themes/core/assets/img/admin/blocks/lead-form/left.svg
> Lead Form Block

- wp-content/plugins/core/core.php
> include template functions

- composer.lock
> Composer update (again).

- wp-content/themes/core/components/link/Controller.php
- wp-content/themes/core/components/link/Link_Controller.php
- wp-content/themes/core/components/link/link.php
- wp-content/themes/core/components/pagination/loop/Controller.php
- wp-content/themes/core/components/pagination/single/Controller.php
- wp-content/themes/core/components/share/Controller.php
* Removes the wrapper arguments from the button component. Calls to the button component that need a wrapper (none currently exist) should use the container component around it.
* Refactors the button controller class to meet the coding conventions that we've been discussing.
* Refactors calls to the link component to use constant references instead of magic strings.
> Unwrap Link Component

- docs/docker/install-guide-for-ubuntu.md
> Creating troubleshooting section for Ubuntu instalation

- composer.json
- composer.lock
- wp-content/themes/core/components/blocks/lead_form/Lead_Form_Block_Controller.php
Updates to the latest version of ACF Image Select which fixes the mixed default return value.
> Updates the image select plugin to latest

- .github/workflows/phpcs.yml
> fixes phpcs

- wp-content/plugins/core/src/Blocks/Blocks_Definer.php
Adds a missing Core block (Quote) that we utilize.
> Add Core Quote block support.

- wp-content/themes/core/components/footer/navigation/navigation.php
- wp-content/themes/core/components/header/navigation/Header_Navigation_Controller.php
- wp-content/themes/core/components/header/navigation/navigation.php
- wp-content/themes/core/components/header/subheader/Subheader_Controller.php
- wp-content/themes/core/components/header/subheader/subheader.php
> Add missing echo’s

- docs/basics/blocks.md
Improves documentation for blocks
> Adds documentation for ACF Blocks

- dev/tests/tests/acceptance/Tribe/Project/Theme/Body_ClassesCest.php
- dev/tests/tests/unit/Tribe/Project/Theme/Config/ColorsTest.php
- dev/tests/tests/unit/Tribe/Project/Theme/Media/Image_WrapTest.php
- wp-content/plugins/core/src/Theme/Config/Colors.php
- wp-content/plugins/core/src/Theme/Media/Image_Wrap.php
Reopens a PR for the still-applicable commits from #485, adding a handful of tests to our suite.
> More tests

- wp-content/plugins/core/src/Blocks/Types/Card_Grid/Card_Grid.php
Returns the borked layout setting for Card Grid Block.
> SQONE-440 Repair merge conflict snafu which removed the layout setting.

- .env.sample
The 1password link moved and we'll now use a short URL we can adjust in the future in the event that happens again.
> Update 1password link in .env.sample

- README.md
- dev/docker/README.md
- docs/getting-started/build.md
- docs/getting-started/installation.md
Hi! Few small improvements in docs.
I've deleted some dead links in the main [README.md](https://github.com/moderntribe/square-one/blob/main/README.md#documentation):
- I've changed some of the links to the closest current readme.
- I've deleted the links I couldn't match.
- I've also changed the command to enter mysql from the same docker instance. So we don't need to have mysql installed in the host machine.
```diff
- mysql -u root -h mysql.tribe -p
+ docker exec -it tribe-mysql mysql -uroot -p
```
Thanks !
N/A
> AGINT-85 Improvements in docs

- .github/workflows/ci.yml
- .github/workflows/phpcs.yml
- composer.json
- composer.lock
- wp-content/plugins/core/src/Blocks/Types/Accordion/Accordion.php
- wp-content/plugins/core/src/Blocks/Types/Buttons/Buttons.php
- wp-content/plugins/core/src/Blocks/Types/Card_Grid/Card_Grid.php
- wp-content/plugins/core/src/Blocks/Types/Content_Columns/Content_Columns.php
- wp-content/plugins/core/src/Blocks/Types/Hero/Hero.php
- wp-content/plugins/core/src/Blocks/Types/Interstitial/Interstitial.php
- wp-content/plugins/core/src/Blocks/Types/Lead_Form/Lead_Form.php
- wp-content/plugins/core/src/Blocks/Types/Links/Links.php
- wp-content/plugins/core/src/Blocks/Types/Logos/Logos.php
- wp-content/plugins/core/src/Blocks/Types/Media_Text/Media_Text.php
- wp-content/plugins/core/src/Blocks/Types/Quote/Quote.php
- wp-content/plugins/core/src/Blocks/Types/Stats/Stats.php
- wp-content/plugins/core/src/Blocks/Types/Tabs/Tabs.php
Per the conversation this week, this change used the tribe-libs new Field_Section to create content sections inside the plugin and out of tribe libs. This is specifically using accordions for the sections. This is dependent on the changes in https://github.com/moderntribe/tribe-libs/pull/69
> Updates fields to use field section accordions

- docs/getting-started/build.md
> Update Build README

- .github/workflows/ci.yml
- changelog.md
- dev/docker/docker-compose.yml
- dev/tests/tests/webdriver/SquareOneChromeExampleCest.php
Attempts to fix CI GitHub Workflow.
- [Link to Issue](https://example.com)
- [Link to Demo](https://example.com)
- [Link to Video](https://example.com)
> Fix CI Workflow

- changelog.md
- wp-content/themes/core/components/blocks/gallery_grid/Gallery_Grid_Controller.php
- wp-content/themes/core/components/routes/index/index.php
- wp-content/themes/core/components/slider/Slider_Controller.php
- wp-content/themes/core/components/slider/css/slider.pcss
- wp-content/themes/core/components/slider/js/slider.js
- wp-content/themes/core/gulp-tasks/postcss.js
- wp-content/themes/core/integrations/gravity-forms/css/controls/file.pcss
- wp-content/themes/core/integrations/swiper/css/_variables.pcss
- wp-content/themes/core/integrations/swiper/css/swiper.pcss
- wp-content/themes/core/package.json
- wp-content/themes/core/yarn.lock
* Updates the swiper js library to latest version
* Addresses issues that were breaking the slider component (incomplete port on my part last year)
* Updated gulp postcss config to preserve custom properties by default and to allow for native use of :focus-within & :focus-visible
> Address slider component issues

- composer.json
- composer.lock
Bumps the version of Tribe ACF Post List field dep to latest.
> ACF Post List field fixes.

- composer.json
- composer.lock
Use the 2.0 version constraint for tribe acf post list plugin so updates in the 2.x version range will make their way here easier.
> composer update for tribe acf post list 2.2.0

- changelog.md
- local-config-sample.php
- wp-content/plugins/core/src/Integrations/Google_Tag_Manager/GTM_Scripts.php
- wp-content/plugins/core/src/Integrations/Google_Tag_Manager/Google_Tag_Manager_Subscriber.php
- wp-content/plugins/core/src/Integrations/Gravity_Forms/Gravity_Forms_Subscriber.php
- wp-content/themes/core/assets/js/src/utils/dom/body-lock.js
- wp-content/themes/core/components/blocks/hero/hero.php
- wp-content/themes/core/components/card/card.php
- wp-content/themes/core/components/document/header/header.php
- wp-content/themes/core/gulp-tasks/cssnano.js
- wp-content/themes/core/gulp-tasks/postcss.js
- wp-content/themes/core/integrations/spinner/css/default.pcss
- wp-content/themes/core/integrations/spinner/index.pcss
- wp-content/themes/core/yarn.lock
This updates a handful of items:
- Updated: refreshed local-config-sample.php to have a more thorough set of constants you may need, especially now that we have a Local environment option.
- Updated: newer version of spin.js requires some css, added that.
- Updated: set a default set of theme image paths for postcss-inline-svg
- Updated: disabled cssnano discarding "unused" keyframes. It was borking the spin.js css.
- Updated: remove the tribe/body_opening_tag action in favor of wp_body_open and updated our GTM implementation to use it.
- Fixed: body-lock.js needed an update to work correctly for safari/ios.
- Updated: added a isLocked check for body-lock.js, it's handy. 
- [SQONE-560](https://moderntribe.atlassian.net/browse/SQONE-560)
- …
> Miscellaneous maintenance

- dev/tests/tests/acceptance/Tribe/Project/Object_Meta/Post_Archive_SettingsCest.php
- dev/tests/tests/acceptance/Tribe/Project/Object_Meta/Taxonomy_Archive_SettingsCest.php
- wp-content/plugins/core/src/Object_Meta/Object_Meta_Definer.php
- wp-content/plugins/core/src/Object_Meta/Post_Archive_Settings.php
- wp-content/plugins/core/src/Object_Meta/Taxonomy_Archive_Settings.php
Adds new meta for use in the basic `archive.php` template.
Basic Post Archive:
- Title
- Description
- Hero Image
Taxonomy:
- Hero Image
- https://moderntribe.atlassian.net/browse/SQONE-279
- [General Archive Settings](http://p.tri.be/OohnT1)
- [Taxonomy Archive Settings](http://p.tri.be/nBfCgt)
> Basic Post Archive Meta

- changelog.md
- composer.json
- composer.lock
- webpack/admindev.js
- webpack/adminprod.js
- webpack/themedev.js
- webpack/themeprod.js
- wp-content/mu-plugins/force-plugin-activation.php
* Fixes an issue related to public paths for JS module resolution. (The paths used for resolution were duplicating the base path like so: `/wp-content/themes/core/wp-content/themes/core/...`.)
* Drop the Composer plugin requirement for Safe SVG. Improved functionality is baked into SquareOne already. See PR #651 & related moderntribe/tribe-libs#71
* Updates the Limit Login Attempts force-activation path per the updated version of the plugin.
> Misc Bug fixes & clean up

- phpcs.xml.dist
Keep getting PHP memory errors due to the size of the cache file, so just removing it.
> Remove phpcs cache file due to memory issues

- wp-content/plugins/core/src/Blocks/Types/Accordion/Accordion.php
Updates/Adds the Field Improvements for the Tab Block Fields.
> [SQONE-612] Accordion Block Field Updates

- docs/tooling/git-hooks.md
- Updates docs to let the user know they should run the lefthook command through yarn
> prefix lefthook command with yarn

- docs/concepts/container.md
Add docs for container auto-complete in PHPstorm
> add docs for container auto-complete in PHPstorm

- composer.json
- composer.lock
Updates WordPress to 5.7.2
Other various minor plugin updates
> Update to WP 5.7.2

- wp-content/plugins/core/src/Routes/Sample_REST_Route.php
- wp-content/plugins/core/src/Routes/Sample_Route.php
- wp-content/themes/core/routes/sample/sample.php
The sample link route was no longer valid after the route folder change. This moves it to the correct place.
> fix sample route

- wp-content/plugins/core/src/Blocks/Types/Content_Columns/Content_Columns.php
https://moderntribe.atlassian.net/browse/SQONE-632
> Updates Content Columns block.

- wp-content/plugins/core/src/Blocks/Types/Icon_Grid/Icon_Grid.php
- wp-content/plugins/core/src/Blocks/Types/Icon_Grid/Icon_Grid_Model.php
- wp-content/themes/core/components/blocks/icon_grid/Icon_Grid_Controller.php
https://moderntribe.atlassian.net/browse/SQONE-633
> Updates Icon Grid Block.

- wp-content/plugins/core/src/Blocks/Types/Buttons/Buttons.php
- wp-content/themes/core/components/blocks/buttons/Buttons_Block_Controller.php
https://moderntribe.atlassian.net/browse/SQONE-630
> Updates Buttons Block.

- composer.json
- composer.lock
Updates plugins to latest versions available. Includes the following:
- ACF
- Disable Emojis
- Gravity Forms (I've confirmed our filter for legacy markup is set and works properly with this version of the plugin.)
- Limit Login Attempts Reloaded
- Redirection
- TEC
- Yoast SEO
> Update plugins to latest versions.

- changelog.md
- wp-content/plugins/core/src/CLI/CLI_Definer.php
- wp-content/plugins/core/src/Core.php
- Adds a default CLI_Definer, fixing: https://github.com/moderntribe/square-one/issues/913
> Add a default but empty CLI Definer

- changelog.md
- wp-content/plugins/core/src/Blocks/Types/Accordion/Accordion.php
- wp-content/plugins/core/src/Blocks/Types/Accordion/Accordion_Model.php
- wp-content/themes/core/assets/js/src/utils/dom/scroll-to.js
- wp-content/themes/core/components/accordion/Accordion_Controller.php
- wp-content/themes/core/components/accordion/js/accordion.js
- wp-content/themes/core/components/blocks/accordion/Accordion_Block_Controller.php
- Adds ability to enable/disable scroll-to functionality for accordion block
- [SQONE-514](https://moderntribe.atlassian.net/browse/SQONE-514)
> [SQONE-514] Accordion Block/Component Refinements

- .deploy/config/nginx.conf
- .deploy/config/php.ini
- changelog.md
- composer.json
- dev/docker/nginx/nginx.conf
* Aligns Dokku NGINX client_max_body_size and PHP max_filesize, and post_max_size
* Adds support for webp and woff2 static file handling to both Docker and Dokku
* Adds a few PHP extensions that WordPress recommends/requires so that Dokku environments are setup properly for WordPress.
> Dokku & Docker config updates

- changelog.md
- package.json
- webpack/configs/app-base.js
- webpack/configs/local.js
- webpack/example.js
- wp-content/plugins/core/src/Assets/Theme/Scripts.php
- wp-content/themes/core/assets/js/src/apps/Example/app.pcss
- wp-content/themes/core/assets/js/src/theme/core/ready.js
- wp-content/themes/core/components/card/js/card.js
- yarn.lock
Updates some of the underlying webpack and related config to get HMR dev working properly with our local dev certs and hostnames. Also some changes due to updated APIs in webpack.
> Webpack & related updates for React app dev (Example et al.)

- changelog.md
Removes the leftover merge conflict lines from my previous commit. 😞 
> fix where I didn't save my merge conflict file

- changelog.md
- composer.lock
- package.json
- wp-content/themes/core/components/slider/Slider_Controller.php
- wp-content/themes/core/components/slider/js/slider.js
- wp-content/themes/core/integrations/swiper/css/_variables.pcss
- wp-content/themes/core/integrations/swiper/css/swiper.pcss
- yarn.lock
Updates Swiper to the most recent version including the following changes:
- Update Swiper styles to newest version, remove prefixed calls (since they get prefixed by us anyway), as well as update the variables file to include some new variables.
- Update `swiper` import call in `components/slider/js/slider.js`
- Update `swiper-container` class in `components/slider/Slider_Controller.php` to `swiper`
As far as I can tell from my testing of using the slider component, there are no breaking bugs in our implementation. Likely though, there may be some issues if this was implemented into an older site.
- [SQONE-697](https://moderntribe.atlassian.net/browse/SQONE-697)
> [RFC / SQONE-697] update swiper version

- changelog.md
- wp-content/themes/core/components/content_block/Content_Block_Controller.php
I ran into an issue when trying to override the tag used on this component. I've updated this to use the same override logic found in the title method.
> Adds conditional to the content's text component tag.

- changelog.md
- package.json
Updates browserslist to latest versions, removes a number of dead browser keys.
> Modernize browserlist.

- phpstan-baseline.neon
- phpstan.neon.dist
- wp-content/plugins/core/src/Block_Middleware/Block_Middleware_Definer.php
Many things improved since last baseline creation.
> Clean up PHPStan ignores

- changelog.md
- package.json
- phpstan-baseline.neon
- phpstan.neon.dist
- wp-content/plugins/core/src/Block_Middleware/Block_Middleware_Definer.php
- yarn.lock
From https://github.com/moderntribe/square-one/pull/1068
> Clean up PHPStan ignores (#1068)

- changelog.md
- dev/docker/docker-compose.yml
- Updates to the latest docker-compose.yml syntax to prevent errors as per https://github.com/docker/compose/issues/10411
> Update docker-compose.yml for docker compose v2.17.x
