moderntribe/square-one

gulp_tasks/uglify.js

Updates gulp uglify task so that Swiper library is included in the vendor JS file. Without this, Swiper JS doesn't load for environments with `SCRIPT_DEBUG` set to false. 
More context in Slack, here: https://tribe.slack.com/archives/C02595YKF/p1567557114007700

Bugfix/Include swiper with vendor JS

---

dev/docker/docker-compose.yml

Sets the `PAGER` environment variable to `more` so that WP CLI commands that use the pager don't complain when `less` isn't available.
```
sh: 1: less: not found
```
Alternatively, we could just add `less` to our `Dockerfile`. I don't particularly have a preference between the two approaches.
Re-opens https://github.com/moderntribe/square-one/pull/338

set PAGER environment variable

---

changelog.md
wp-content/plugins/core/src/Templates/Components/Container.php
wp-content/themes/core/components/container.twig

Added container component. I found myself needing a simple wrapper component that can take aribtrary html and have a custom tag, classes and attributes. It allows me to compose more complex ui's in controllers while following our rule of no html strings in controllers, which i have seen happening in some places around projects. An example usage from a reasonably complex hero panel/slider i had to compose, the slide creator:
```php
/**
* Composes a hero pane, either for use in the slider or for use on its own.
*
* @param array $data
* @param int $index
* @return string
*/
protected function get_slide( $data = [], $index = 0 ): string {
$left_html = $this->get_left_rail_image( $data );
$left_html .= $this->get_left_image( $data[ HeroPanel::FIELD_SLIDE_IMAGE ] );
$right_html = …
```

Add container component

---

changelog.md
gulp_tasks/watch.js
package.json
wp-content/themes/core/js/src/theme/core/ready.js
yarn.lock

With our hybridized build system that allows for injection of react apps as chunks into our main bundles, I ran into one tweak that optimizes build so we arent wasting time.
When you are wanting to work on a react app, you set HMR_DEV true in your local config and fire up the npm task for the react app you want to be working on. The main js bundle then compiles WITHOUT the chunk loading for react apps, as you have a webpack dev server loading an HMR enabled version of your app and this would cause your app to be loading twice, one stale.
Now a problem, when you want to be devving on your main js bundles, admin or theme, your shared react apps are going to be compiled as chunks on every watch reload, a painful experience. So, our dev task, when instantiated by watch, needs to know to …

Optimize dev flows for no react

---

changelog.md
wp-content/plugins/core/src/Panels/Caching_Loop.php

This disables panels caching if we're in preview.

Bail if we're in panel preview

---

ansible/group_vars/all/php.yml

The vendor role `geerlingguy.php` sets `expose_php = On` by default.

Adds Ansible setting to disable the expose_php option by default

---

changelog.md
package.json

The path to the docker log.sh scripts (both project & global) were incorrect. This just fixes them.

Bugfix: NPM script path to docker logging scripts.

---

wp-config.php

We recently noticed Glomar's IP detection was not working. It was returning the Load Balancer or Proxy's IP address instead of the original users IP. While we could account for this in the Glomar itself, other plugins or code may not. This fix updates the REMOTE_ADDR server header value if we detect a HTTP_X_FORWARDED_FOR server header exists, which is what the LB and or Proxy is providing from the original users.
I assume this is safe as it's the recommended approach I've found. We could instead simply patch Glomar, but this is a silent issue and will likely happen again if we don't fix it at a higher level.
Debate welcome.

SQ1 + LoadBalancer != real user ip address

---

wp-content/plugins/core/src/Twig/Twig_Definer.php

Just did this for LL in https://github.com/moderntribe/little-league/pull/428
I think it should be the standard config in the upcoming Template refactor.

Allow us to set `opcache.validate_timestamps=0` in php.ini

---

wp-content/plugins/core/src/Theme/Resources/Editor_Styles.php
wp-content/plugins/core/src/Theme/Theme_Subscriber.php

Enqueues the full front-end stylesheet for the block editor, keeping the existing `editor-style.css` for the classic editor.

Block editor styles

---

changelog.md
dev/docker/global/cert.sh

There is a [requirement](https://cabforum.org/2017/03/17/ballot-193-825-day-certificate-lifetimes/) that has recently gone into effect that certificates can only be created for a maximum of 825 days.
The updates set a default number of days to 825 which can be overridden by adding the number of days you would like after the domain option.  This allows you to continue to set the certs to 10 years if you are running on a system that still excepts the larger certificate expiration time. 
```sh
./cert.sh domain.tribe 365
```
Overrides the default expiration from 825 days to 365 from today.
```sh
./cert.sh domain.tribe
```
domain.tribe's certificate will expire 825 days from today.

Updates certificate expiration days to match 825 day requirement.

---

changelog.md
dev/docker/global/start.sh

The return from the latest version of Alpine was returning inconsistent results  when calling nslookup.  This was keeping host.tribe from being available to the container and keeping xDebug from being able to find the host computer.
This change forces the use of alpine:3.10 in order to provide consistant results  when querying docker.for.mac.locahost.

Fixes Alpine nslookup failure when using latest build

---

wp-content/plugins/core/src/Blocks/Types/Accordion.php

Revert the change to layout option args. The issue is in gutenpanels, not in our registration code.

Revert "Fix accordian key and value for image options"

---

composer.lock
wp-content/plugins/core/src/Blocks/Types/Accordion.php

Per the scope in https://moderntribe.atlassian.net/browse/SQONE-358, Accordion blocks should have a tagline, but should not have layout options.

add tagline field for accordion

---

wp-content/themes/core/assets/js/src/admin/core/plugins.js
wp-content/themes/core/assets/js/src/admin/core/ready.js
wp-content/themes/core/assets/js/src/admin/editor/index.js
wp-content/themes/core/assets/js/src/admin/editor/preview.js
wp-content/themes/core/assets/js/src/admin/editor/types.js
wp-content/themes/core/assets/js/src/theme/core/components.js
wp-content/themes/core/assets/js/src/theme/core/integrations.js
wp-content/themes/core/assets/js/src/theme/core/ready.js
wp-content/themes/core/components/accordion/js/accordion.js
wp-content/themes/core/components/comments/js/comments.js
wp-content/themes/core/components/share/js/share.js
wp-content/themes/core/components/slider/js/slider.js
wp-content/themes/core/components/tabs/js/tabs.js
wp-content/themes/core/components/video/js/video.js
wp-content/themes/core/integrations/gravity-forms/js/gravity-forms.js

We need to run some theme js and plugins in the gutenberg editor. This sets up a chunk to do that and runs our lazyloading scripts. Since we are using mutation observers in lazysizes, coming back from edit ui or any deferred loading of lazy images works as expected.
Next up we'll probably start bring in the theme side  component js as needed, eg the slider scripts, but have to setup an event system for that to work with the above concern.

Editor Theme Scripts

---

wp-content/plugins/core/src/Integrations/Gravity_Forms/Form_Styles.php
wp-content/plugins/core/src/Integrations/Gravity_Forms/Gravity_Forms_Subscriber.php

Disables all gravity form styles by filtering the option to enable/disable them. This is to address form styling issues in the block editor. https://moderntribe.atlassian.net/browse/SQONE-308?focusedCommentId=75871
This has the consequence of disabling _all_ of the gform style, and I'm not sure if that's really what we want. We had been dequeuing just `gforms_formsmain_css`. This filter will also dequeue:
- `gforms_reset_css`
- `gforms_datepicker_css`
- `gforms_ready_class_css`
- `gforms_browsers_css`
It looks OK to me, but I don't have the knowledge to know if this is correct.
@jamiepaul, can you let me know if this works?

disable all gravityform styles - SQONE-308

---

wp-content/plugins/core/functions/templates.php
wp-content/plugins/core/src/Theme/Media/Oembed_Filter.php

Fixes the Oembed filter
@jbrinley question on this. Ryan and I were talking and we can see instances where a "dumb" component may need to be generated in a higher Controller and using `get_template_part` without the output buffer won't work. Do you see any value in having a `tribe_get_template_part` wrapper with an optional `$echo` arg in case this becomes a thing? Obviously we don't want a ton of output sitting in memory but interested on your thoughts here.

Save markup in output buffer and actually return it once cached

---

wp-content/plugins/core/src/Templates/Components/Traits/Page_Title.php
wp-content/themes/core/components/document/head/Controller.php
wp-content/themes/core/components/header/subheader/Controller.php
wp-content/themes/core/components/header/subheader/subheader.php
wp-content/themes/core/components/text/Controller.php

This implements the `page_title` method as a trait that is now globally available and makes use of it along with a proper page title in the subheader component. I also updated the text component based on something I missed as part of the greater done component clean up pass.
Dave, I could see us adding some additional args and even variations to subheader in the future, but I think can wait until we start using and finish building out the base theme.

Implement subheader page title and update text component

---

wp-content/themes/core/components/content/single/index/index.php
wp-content/themes/core/components/routes/page/page.php

Remove outer l-container for page & post singles since this has to be done at a different level to accommodate "panel" blocks in the_content.

Remove Outer `l-container`

---

dev/tests/tests/integration/Tribe/Project/Templates/Components/Abstract_ControllerTest.php
wp-content/plugins/core/src/Templates/Components/Abstract_Controller.php

Adds methods to the `Abstract_Controller` to support consistently parsing args in subclasses. Next step after merging this is to start applying the pattern to existing classes.

method to consistently parse args in template controllers

---

wp-content/themes/core/components/container/container.php

If the container template has no content, abort rendering to avoid an empty container.

abort container template if empty

---

wp-content/themes/core/components/button/Button_Controller.php
wp-content/themes/core/components/button/Controller.php
wp-content/themes/core/components/button/button.php

- Removes the wrapper arguments from the button component. Calls to the button component that need a wrapper (none currently exist) should use the container component around it.
- Refactors the button controller class to meet the coding conventions that we've been discussing. Don't like something here? Let's have a conversation about it; this is one possible path, but not the only possible path.

Unwrap button component

---

wp-content/themes/core/components/content_block/Content_Block_Controller.php

Allows the Content_Block component to still work (not throw an error) if not all 4 fields are populated.

Allow missing content args in Content_Block

---

wp-content/plugins/tribe-json-ld/JSONLD/Post_Data_Builder.php

Updates the Tribe JSON LD plugin to fix PHP deprecation notices related to WordPress (Yoast) SEO.
Related docs from Yoast SEO: https://developer.yoast.com/blog/yoast-seo-14-0-using-yoast-seo-surfaces/

Fix for YoastSEO 14.0 deprecation notices.

---

wp-content/themes/core/components/blocks/links/Links_Block_Controller.php
wp-content/themes/core/components/blocks/links/css/links.pcss

This brings the Links block up to date w/ designs to date. Updates links block class naming to follow conventions set in pivot work. Sets override styles for content block component block w/ inline layout specific to Links block design.

Links block design pass

---

wp-content/plugins/core/src/Core.php

Removes `Twig_Definer` from the default list of tribe-libs packages we instantiate from `Core`.

remove twig definer from default list in Core

---

wp-content/plugins/core/src/Blocks/Blocks_Definer.php

Updates the slug from `core/custom-html` to `core/html` in order to give access to the core HTML block. 
- #626 

Updates slug name for Core Custom HTML block.

---

composer.json
composer.lock
wp-content/mu-plugins/force-plugin-activation.php

Adds the WP Tota11y plugin for dev & QA. We used to inject the script as an NPM package and separate JS equeue as part of the SquareOne build. This was removed when the build system was refactored as part of FF.  QA has asked that we bring it back as it's useful for QA'ing. And, frankly, it's helpful for dev as well.
I'm proposing we just rely on a 3rd-party plugin for this rather than making it a part of the Sq1 build system. As it is setup in this PR, the plugin will be force-deactivated if WP_DEBUG is false (or Production), and it will be available to network admins to activate only (in multisite).

SQONE-498 Add Tota11y plugin for dev & testing. 

---

docs/concepts/components.md

Rewrites the component docs to match our new templating paradigm. No more references to Twig or Contexts. Explains how to use `get_template_part()` and our related wrappers.
I'm sure there's more to add to this, but it's a start.

rewrite component docs for new paradigm

---

.editorconfig

The previously defined glob for .pcss files did not resolve properly the editor would not apply editor config settings.
Updates the glob for `.pcss` files.
- [Link to Issue](https://example.com)
- [Link to Demo](https://example.com)
- [Link to Video](https://example.com)
- Open your editor and verify that `.pcss` files use tabs instead of spaces when auto-formatted.

Update .editorconfig pcss rule

---

.editorconfig

The previously defined glob for .js files did not resolve properly so the editor would not apply editor config settings.

Update .editorconfig js rule

---

wp-content/themes/core/assets/js/src/admin/core/block-styles.js
wp-content/themes/core/assets/js/src/admin/core/ready.js

Adds a consistent location to remove the core block styles that are registered client-side since they [cannot be removed](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#unregister_block_style) using the server-side `unregister_block_style` function.

adds ability to remove core block styles

---

changelog.md
docs/concepts/object-cache.md

Fixes typo in object-cache docs.

Fix cache docs typo

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml
wp-content/themes/core/assets/css/src/theme/forms/_variables.pcss
wp-content/themes/core/assets/js/src/admin/core/block-styles.js
wp-content/themes/core/assets/js/src/admin/editor/hooks.js
wp-content/themes/core/assets/js/src/utils/dom/deepscroll.js

This should get deploys running again, forcing use of composer v1 and skipping `yarn validate` for now.

Force deployments to use composer v1 and don't yarn validate

---

changelog.md
dev/docker/docker-compose.yml

Use the minor version of the docker image to continue to get patch updates. `74-2.1` would pull the version that forces composer v1.
None.
- [ x] No, this doesn't need tests because it's a configuration update

Use 74-2.1 to ensure composerv1

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml

Fixes error with ssh-agent:
`Error: Unable to process command '##[set-env name=SSH_AUTH_SOCK;]/tmp/ssh-auth.sock' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/`

Updates ssh-agent GH action.

---

wp-content/plugins/core/src/Blocks/Blocks_Definer.php

Fixes a typo causing the classic editor block to not be available.  The[ classic block is named](https://github.com/WordPress/gutenberg/tree/master/packages/block-library/src/freeform) `core/freeform`.

Corrects the name for the Classic Block in the allow list.

---

README.md

Travis tests were failing - because we don't use Travis anymore. Changed the build badge to GHA.

remove travis badge for gha badge

---

wp-content/plugins/core/src/Blocks/Types/Gallery_Grid/Gallery_Grid_Model.php

Updates an incorrect default from string to array

fixing the Gallery grid default to an array instead of a string

---

wp-content/plugins/core/README.md

Removes links from the Backend Readme that no longer exist. I believe all documentation is now just in the `/docs` folder. I also removed 2 of the plugins that I believe are no longer being used.

Remove old backend doc links

---

docs/concepts/components.md

Adds documentation around the process for loading/building component Javascript.
Closes #698 
- [Build Process Doesn't Compile Component JS Automatically](https://github.com/moderntribe/square-one/issues/698)

Document how component JS is loaded

---

changelog.md
package.json

Stops husky hooks from running phpcs on every PHP file in the project and only looks in our core plugin/theme.
- Do some bad PHP in either `wp-content/plugins/core/ ` or `wp-content/themes/core/` and it will find it.
- Add a premium plugin to `wp-content/plugins` and it will no longer scan it.

Fix husky hooks phpcs from checking every PHP file on commit

---

.github/dependabot.yml
composer.json
composer.lock

Adds the now native Github Dependabot config. This provides some nice benefits:
1. Automatic PRs for dependency updates
2. Schedule dependabot checks interval
3. PR tagging for dependency updates. 
Can read more here: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

add dependabot dependencies management to SQ1.

---

local-config-sample.php
wp-config-environment.php
wp-content/mu-plugins/force-plugin-activation.php

- There wasn't a proper check of `WP_ENVIRONMENT_TYPE` before trying to set the environment based on the legacy `ENVIRONMENT` constant.
- With the existing configuration, tribe glomar is not automatically enabled out of the box and it should be. Someone will immediately notice if that's enabled on production, but it would take a long time for someone to notice their dev/staging server is open to the world.
- 

WP_ENVIRONMENT_TYPE double define bugfix / properly enable glomar

---

.github/workflows/README.md
.github/workflows/ci.yml
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml
.github/workflows/phpcs.yml

GitHub already provides us with secret token to use that has access to the current repo: https://docs.github.com/en/actions/reference/authentication-in-a-workflow
This way when cloning this framework a user no longer needs to create a GH_TOKEN manually.

Use GitHub provided GITHUB_TOKEN secret

---

.github/workflows/ci.yml

Makes CI run on the main branch for Push and Pull_Request. This should fix our  badge and also reduce unnecessary test runs.

[SQONE-603] Limit CI tests to only PR's against the main branch

---

wp-content/themes/core/components/routes/single/single.php

- Fixes the broken author link in the single template
- Removes deprecated function `the_author();`
Fixes this:

Fix broken author link in single meta

---

.github/workflows/eslint.yml

Automated eslinting is broken via GitHub actions, this fixes it by:
- Automatically detecting the node version.
- Using yarn install instead of npm install.
- Using a proper glob pattern to detect changes in our core/theme plugin.
- Using the built in `GITHUB_TOKEN`.
- Properly failing on any errors.
- Break a JS file in the core theme or plugin when a branch is in PR and it should properly fail.
- Fix the issue and push and it should then the action should pass.

Fix eslint GitHub actions

---

wp-content/plugins/core/src/Integrations/Yoast_SEO/Yoast_SEO_Subscriber.php

- Future proofing this as ran into it on another project with strict types as Yoast passes `null` type by default.

Force types for Yoast open graph filters

---

wp-content/plugins/core/src/Nav_Menus/Nav_Attribute_Filters.php
wp-content/plugins/core/src/Nav_Menus/Nav_Menus_Subscriber.php
wp-content/plugins/core/src/Nav_Menus/Walker/Walker_Nav_Menu_Primary.php

Getting ahead of another casting issue we ran into on another project.
WordPress claims the $args are an array, but they cast it as an object in a function.
- Menus on the frontend will no longer throw an error once types are added. 

Proper wp_nav_menu() $args type

---

docs/tooling/phpcs.md

After some research, @ChrisMKindred, @tjdunklee, and I found that the original PHPCS extension doesn't actually work with our coding standards. [PHP Sniffer & Beautifier](https://marketplace.visualstudio.com/items?itemName=ValeryanM.vscode-phpsab) works out-of-the-box and this PR updates the documentation to reflect that finding.

Update VS Code PHPCS Documentation

---

changelog.md
package.json
wp-content/plugins/core/src/Object_Meta/Object_Meta_Definer.php
wp-content/plugins/core/src/Settings/Post_Settings.php
wp-content/plugins/core/src/Settings/Settings_Definer.php
yarn.lock

Moves the Post Archive Settings for Title, Description, and Image under the Post Settings screen. Previously this was a part of "General Settings" which was confusing. Moving it under the Post Menu is a better User Experience.
- [JIRA TICKET](https://moderntribe.atlassian.net/browse/SQONE-643?atlOrigin=eyJpIjoiZDAwM2EwZTMzZGExNGFlZmE5YTczYjIwYjk0YzY2MjAiLCJwIjoiaiJ9)
- [Link to Demo](https://sq1-pr804.moderntribe.qa/wp-admin/edit.php?page=edit-php-settings&secret=1)
- [Link to Video](http://p.tri.be/mUAMqq)

Feature/sqone 643/move post archive settings

---

composer.json
composer.lock

- Updates tribe libs to v3.4.4
- Updates ACF Pro to 5.9,8
- Updates Yoast to 16.7
- Bug fixes for cron queues and routes

bump acf, yoast and tribe-libs to the latest 3.4.x version

---

composer.json
composer.lock

Adds Symfony/Laravel `dd()` command for quick debugging needs via require-dev. Often when I just need a quick dump I find myself wanting the convenience of the `dd()` command from Laravel. I propose we add it to squareone dev dependencies.

Add require-dev symfony/laravel dd package

---

changelog.md
webpack/admindev.js
webpack/adminprod.js
webpack/themedev.js
webpack/themeprod.js

Repairs the url path for dynamic imports in webpack while running the dev tasks. Without the publicPath property set, dynamic imports are referenced from the root of the site, not their correct path within the theme asset folders. 
- [Link to Issue](https://moderntribe.atlassian.net/browse/SQONE-652)
- [Screenshot of broken path for dynamic import](http://p.tri.be/Y0SNsW)

Bugfix/sqone 652/webpack public path

---

changelog.md
gulp-tasks/postcss.js
package.json
yarn.lock

Update PostCSS config to reduce compiled CSS duplication & provide documentation around PostCSS config options.
`postcss-preset-env` handles several of the transforms we had previously outlined independently in our CSS configuration. This change removes those duplicate transforms and adds some notes to the PostCSS config so devs may modify the config as needed on a project-by-project basis.
- [Link to Issue](https://moderntribe.atlassian.net/browse/SQONE-658)
- [Link to Slack conversation](https://tribe.slack.com/archives/G0166CKG8P7/p1627143504016300)

SQONE-658 Remove duplication from compiled CSS

---

wp-content/plugins/core/src/Blocks/Types/Quote/Quote.php

- Fixes duplicate keys in the Quote block example so it renders the preview properly.
Block preview now shows values properly

Fix duplicate keys/broken quote example

---

wp-content/plugins/core/src/Theme/Pagination_Util.php
wp-content/themes/core/components/pagination/loop/Loop_Pagination_Controller.php

- When running phpcbf with the v2 standards, the `$links_offset` will be typed as a `bool` and will break since integers are being passed to it and it's used as an integer in the code. This updates it to the v2 standards.
- Pagination should work as before.

Fix invalid comment type and adjust for mt coding standards v2

---

wp-content/themes/core/components/comments/comment/Comment_Controller.php
wp-content/themes/core/components/comments/comment/comment.php
wp-content/themes/core/components/comments/comments_section/Comments_Section_Controller.php

Fixes an invalid markup error in comments markup.
When running the callback function in `Comments_Section_Controller::get_comments` we were returning the closing markup element. The callback is being called from the `start_el` of the walker which means that we shouldn't be closing the element, the `end_el` will handle that.
This PR also allows the comment controller to use the same comparison in order to output the element (li or div) based on the style in `wp_list_comments` the same way that the `end_el` method does for better compatibility.
- [invalid HTML example Current Output](http://p.tri.be/AsbKC1)
- [Fixed HTML after PR applied](https://sq1-pr854.moderntribe.qa/hello-world/)

fixes markup closing issue in comments

---

wp-content/themes/core/assets/css/src/admin/block-editor/blocks.pcss
wp-content/themes/core/assets/css/src/theme/layouts/default.pcss
wp-content/themes/core/routes/unsupported_browser/css/unsupported-browser.pcss

Updates our style selectors to allow the Core Reusable Pattern "block" and Group blocks to go full-width in the editor and within the `l-sink` context.
[Link to Issue](https://moderntribe.atlassian.net/browse/SQONE-664)
[Demo Link](https://sq1-pr861.moderntribe.qa/wp-admin/post.php?post=214&action=edit)

Bugfix/sqone 664/reusable block width

---

changelog.md
wp-content/themes/core/assets/js/src/theme/core/components.js
wp-content/themes/core/components/footer/navigation/navigation.php
wp-content/themes/core/components/navigation/Navigation_Controller.php
wp-content/themes/core/components/navigation/index.js
wp-content/themes/core/components/navigation/index.pcss
wp-content/themes/core/components/navigation/navigation.php

Adds a generic navigation menu component to SquareOne. This component will be used to disassociate the nav menu implementation from the context it appears in (masthead/footer/legal, etc). In future PRs I'll apply this component to SquareOne's menu locations.
[SQONE-521]
[SQONE-519]
[SQONE-521]: https://moderntribe.atlassian.net/browse/SQONE-521
[SQONE-519]: https://moderntribe.atlassian.net/browse/SQONE-519

SQONE-521 Add a generic navigation menu component.

---

.github/workflows/ci.yml
changelog.md
composer.json
composer.lock

- The owner of https://github.com/hautelook/phpass deleted their repo, which is in the dependency tree of `wp-browser`
- Replaces it with the https://packagist.org/packages/bordoni/phpass fork until wp-browser internalizes the dependency. 
- Updates wp-browser to 3.0.9

Update wp-browser to 3.0.9

---

changelog.md
wp-content/plugins/core/src/Assets/Admin/Styles.php
wp-content/plugins/core/src/Assets/Assets_Subscriber.php

Bugfix for editor styles regression due to reset.css enqueued in the block editor in version 5.8 of WordPress Core.
- [Link to Issue](https://moderntribe.atlassian.net/browse/SQONE-667)

SQONE-667: 

---

package.json
webpack/configs/app-base.js
webpack/example.js
webpack/rules/styles.js
wp-content/plugins/core/src/Assets/Theme/Scripts.php
yarn.lock

After upgrading to webpack 5, the dev mode for react apps was broken. I have updated the configuration to get it working again.
Next steps:
- Enable HTTPS in dev mode. Seems quite complex as you have to generate and sign certificates on each device.
- Enable HMR (Hot Module Replacement) with Live Reload. In theory it is configured but it's not working.
- Update example app reducing its complexity (bye redux/sagas). Include a basic example with [`@moderntribe/faceted-loops`](https://github.com/moderntribe/faceted-loops)?
Other ideas:
- Try to use `@wordpress/scripts` to run our react apps
- Integrate react apps as gutenberg blocks
No, this doesn't need tests because I have changed only some webpack settings

Support react apps in dev mode

---

changelog.md
wp-content/plugins/core/src/Nav_Menus/Nav_Attribute_Filters.php

Improves the classes added to nav menu elements by supporting the `menu` parameter (of `wp_nav_menu()`). See #880.
After creating two menus (`sample` and `primary`) and assigning one of them to the `primary` theme location, added the following code to an mu-plugin to easily test the proper output:
```php
<?php declare(strict_types=1);
use Tribe\Project\Nav_Menus\Menu;
add_action( 'wp_body_open', function() {
// Test theme_location parameter.
echo Menu::menu( [
'theme_location' => 'primary',
'container_class' => 'test-1 location-primary',
] );
// Test menu parameter.
echo Menu::menu( [
'menu' => 'sample',
'container_class' => 'test-2 menu-sample',
] );
// Test menu and theme_location parameter.
echo Menu::menu( [
'menu' => 'sample',
'theme_location' => 'primary', …
```

Apply nav menu classes only if `theme_location` parameter is populated

---

package.json
yarn.lock

Rolls back the version of one webpack dependency due to the update breaking the watch task:
```[09:20:07] Using gulpfile ~/Projects/squareone/htdocs/gulpfile.js
[09:20:07] Starting 'dev'...
[09:20:07] Starting 'watch:frontEndDev'...
[09:20:07] Starting 'watch:watchAdminJS'...
[09:20:07] Starting 'watch:watchThemeJS'...
[09:20:07] Starting '<anonymous>'...
[09:20:07] 'watch:watchAdminJS' errored after 143 ms
[09:20:07] TypeError: Invalid value used in weak set
at WeakSet.add (<anonymous>:null:null)
at MiniCssExtractPlugin.apply (/home/dpe/Projects/squareone/htdocs/node_modules/mini-css-extract-plugin/dist/index.js:385:18)
at webpack (/home/dpe/Projects/squareone/htdocs/node_modules/webpack-stream/node_modules/webpack/lib/webpack.js:51:13)
at Stream.<anonymous> …
```

SQONE-683 Rollback mini-css-extract version update due to breaking change

---

changelog.md
composer.json

- [composer 2.2+](https://github.com/composer/composer/releases/tag/2.2.0) has added an `allow-plugins` configuration value, which then asks you if you want to allow each plugin in your composer.json. This adds our current plugin configuration. We could alternatively allow all plugins with `allow-plugins: true` as well. 
Projects that newly pull the `moderntribe/squareone-php7.4-3.0` image will be asked to add their plugins to their composer.json as well, and can do so once [so 5.5.1 bugfix](https://github.com/moderntribe/square1-global-docker/pull/102) is released.
Running `composer install` when using composer v2.2+ should no longer ask you if you want to enable these plugins and function as normal.

Add composer v2.2+ allowed plugins

---

.github/workflows/phpcs.yml
changelog.md

- Bad copy pasta of the composer token. Props @lindseyolson for pointing it out!

Use correct secret/token for composer

---

changelog.md
wp-content/themes/core/components/blocks/gallery_slider/js/gallery-slider.js
wp-content/themes/core/components/slider/js/slider.js

In the slider component JS, the imagesReady event is added to the sliders after they have already been initialized. This leads to unpredictable triggering of the imagesReady event since in some cases, the slider images have already been loaded by the time the event is added.
This PR adds the event listener during initialization of a `Swiper` instance to ensure it is always triggered. It also updates the `modern_tribe/swiper_images_ready` custom event to pass the current swiper instance when that event is triggered, allowing easier access to the Swiper instance and all of its parameters and methods.

[SQONE-684] Swiper imagesReady event listener

---

changelog.md
wp-content/themes/core/components/share/js/share.js

The JS for the social-share component uses the first instance of itself as the container element. This prevents the JS events from being delegated to additional instances of the component (such as a single post with share icons in the header and footer). 
This PR allows for an indefinite number of social share components to be used on a page.
- [Link to Demo](https://sq1-pr.moderntribe.qa/post-49/)

[SQONE-644] Fix social share pop for multiple components

---

changelog.md
wp-content/themes/core/components/accordion/js/accordion.js
wp-content/themes/core/components/blocks/gallery_slider/js/gallery-slider.js
wp-content/themes/core/components/card/js/card.js
wp-content/themes/core/components/tabs/js/tabs.js
wp-content/themes/core/integrations/gravity-forms/js/gravity-forms.js

There are a number of components that are able to initialize their JavaScript even when the component is not present on a page. This PR updates those components so that any required JS is only loaded when necessary.
**Components Addressed:**
- Accordion
- Card
- Tabs
- Gallery Slider Block
- Gravity Forms
- [Link to Demo](http://sq1-pr.moderntribe.qa/)
- [Console Log showing init of non-present components](http://p.tri.be/M4vc9o)

Reduce unnecessary JavaScript initialization

---

changelog.md
dev/docker/nginx/nginx.conf

If your production host for proxying images is behind Cloudflare, the image proxy will fail without this addition to support SNI SSL certificates.
- A production domain configured in nginx.conf that is behind Cloudflare will now display images on your local environment.

Add proxy_ssl_server_name on; for nginx image proxy

---

wp-content/plugins/tribe-glomar/Tribe_Glomar.php

In some cases `COOKIE_DOMAIN` will return a bool. This always casts it as a string JIC.

Fix cookie type issue

---

changelog.md
composer.json
composer.lock

* Changed: Replaced `msawicki/acf-menu-chooser` with a forked https://github.com/moderntribe/acf-menu-chooser that includes security fixes and is also added to packagist.
* Updated: ACF (5.12), Tribe Libs (3.4.10), Redirection (5.2.3), Yoast (18.2), TEC (5.14.0.4)
Everything should work as before.

Forked acf menu chooser plugin + plugin and dependency updates

---

changelog.md
wp-content/mu-plugins/force-plugin-activation.php

Just ran into this on another project, the `get_current_screen()` function is not guaranteed to be available depending on what's calling the `all_plugins` filter, in this case Jetpack Sync, which collects plugin data outside of a screen scope.
Example error logs:
```
PHP Fatal error:  Uncaught Error: Call to undefined function Tribe\\Mu\\get_current_screen() in /nas/content/live/sitenamehere/wp-content/mu-plugins/force-plugin-activation.php:180\nStack trace:\n#0 /nas/content/live/sitenamehere/wp-includes/class-wp-hook.php(292): Tribe\\Mu\\Force_Plugin_Activation->hide_from_blog(Array)\n#1 /nas/content/live/sitenamehere/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)\n#2 /nas/content/live/sitenamehere/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/class-func …
```

Bugfix for Jetpack sync fatal errors w/ force plugin activation

---

changelog.md
wp-content/themes/core/assets/css/src/theme/typography/lists.pcss

- Ensures list bullets and numbers are reflected in nested lists for regular and stylized lists under `t-sink`
- [SQONE-567](https://moderntribe.atlassian.net/browse/SQONE-567)

[SQONE-567] Fixes nested bullets/numbers on lists

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-review-app.yml
.github/workflows/deploy-stage.yml
.github/workflows/deploy-test.yml
.github/workflows/dokku-deploy.yml

* Missing Review app PR number after we abstracted the GHA tasks to `moderntribe/actions`
* Also removed any push deploy events, those should be opt-in when the project is setup.

Add missing pr number to review app workflow

---

changelog.md
composer.lock
wp-content/themes/core/blocks/accordion/accordion.php
wp-content/themes/core/blocks/buttons/buttons.php
wp-content/themes/core/blocks/cardgrid/cardgrid.php
wp-content/themes/core/blocks/contentcolumns/contentcolumns.php
wp-content/themes/core/blocks/contentloop/contentloop.php
wp-content/themes/core/blocks/gallerygrid/gallerygrid.php
wp-content/themes/core/blocks/galleryslider/galleryslider.php
wp-content/themes/core/blocks/hero/hero.php
wp-content/themes/core/blocks/icongrid/icongrid.php
wp-content/themes/core/blocks/interstitial/interstitial.php
wp-content/themes/core/blocks/leadform/leadform.php
wp-content/themes/core/blocks/links/links.php
wp-content/themes/core/blocks/logos/logos.php
wp-content/themes/core/blocks/mediatext/mediatext.php
wp-content/themes/core/blocks/quote/quote.php
wp-content/themes/core/blocks/sectionnav/sectionnav.php
wp-content/themes/core/blocks/spacer/spacer.php
wp-content/themes/core/blocks/stats/stats.php
wp-content/themes/core/blocks/tabs/tabs.php

- All block models were statically instantiated across many views using the `new Block_Model()` keyword. This prevents developers from taking advantage of PHP-DI's dependency injection/autowiring/decorating etc. With this change, we can freely inject dependencies into block models or modify the Base_Model based on project needs.
Nothing should appear different.

Feature: instantiate block models with the container instead of statically

---

.gitignore
.vscode/extensions.json
changelog.md

Adds a popup to VSCode if you do not have the recommended extensions installed, suggesting that you install them. The recommended extensions are: 
- EditorConfig (for utilizing our editor config settings)
- xDebug (for debugging PHP)
- PHP Sniffer & Beautifier (for PHPCS)
- [Screenshot of Recommended WorkSpace Extensions](http://p.tri.be/F0bg0K)

Feature: Adds Recommended Extensions for VSCode

---

changelog.md
dev/tests/tests/unit/Tribe/Project/Integrations/ACF/Max_Length_CounterTest.php
wp-content/plugins/core/src/Core.php
wp-content/plugins/core/src/Integrations/ACF/ACF_Subscriber.php
wp-content/plugins/core/src/Integrations/ACF/Max_Length_Counter.php

Adds an ACF helper class that triggers a max character counter on input or textarea fields that include a maxlength value. For every project I have worked on, there has been a request for this feature and the level of discovery/lift always kept us from getting it added. 
I have included example usage in the video below.
- [Link to Video](http://p.tri.be/4nsXJG)

Feature/Discussion: ACF Maxlength Helper Function

---

wp-content/plugins/core/src/Integrations/Gravity_Forms/Form_Markup.php

Many undefined index errors occur in the Gravity Forms form editor when adding fields to a form. `inputType` is no longer passed w/ field data and field type enhancements (i.e. enableEnhancedUI for select dropdowns) only have the corresponding key when checked. 

Fix Gravity Forms undefined index errors

---

.vscode/extensions.json
changelog.md

Adds the PHP Intelephese VS Code extension to allow for PHPStorm Metadata autocompletion.  This also helps with compatibility between IDE's in #987. 
- [Screenshot](http://p.tri.be/mjxoAQ)

Adds PHP Intelephese to Recoomended VS Code extentions

---

changelog.md
wp-content/themes/core/assets/js/src/utils/data/update-query-var.js
wp-content/themes/core/assets/js/test/tests/utils/data/update-query-var.test.js

The `updateQueryVar` utility was not properly removing query vars set to `undefined`. This fix pulls in a version of `updateQueryVar` that adds all necessary functionality. This fix also includes tests for query vars that have an `undefined` value.

fix update query var utility; add tests

---

changelog.md
dev/tests/tests/_support/Classes/Test_Case.php

- Allows the use of `$this->container->get( Whatever::class )` for integration tests. Sometimes you want to actually test the class as the container builds it instead of creating the dependencies manually.
- Should function exactly as before.

Set up the container for use in integration tests

---

.github/workflows/phpcs.yml
changelog.md

- Allows PHPStan to use unlimited memory, at a certain number of files it will always run out and throw errors.
- No more failing CI.

Allow unlimited memory when running PHPStan via CI

---

changelog.md
wp-content/themes/core/components/blocks/_css/block-editor.pcss
wp-content/themes/core/components/blocks/_css/index.pcss

https://moderntribe.atlassian.net/browse/SQONE-574
Blocks on both the front end & back end weren't properly being cleared around floated elements. Since all of our blocks are made to be full width, we can safely add `clear: both;` to all of our blocks.
(sorry about the commit having the wrong ticket tag, that's my bad)
1. Add a floated element
2. Add a SO block below the floated element, this block shouldn't float up beside the floated element.

[SQONE-574]: clear floats on all blocks

---

changelog.md
wp-content/plugins/core/src/Blocks/Types/Stats/Stats.php

- Removes redundant `SECTION_CONTENT` constant in Stats Block
N/A

Improvement: remove stats block redundant constant

---

changelog.md
wp-content/themes/core/components/follow/Follow_Controller.php

Filters empty social items to prevent empty HTML output
VS.

Bugfix: Prevent empty social items

---

changelog.md
docs/basics/blocks.md
wp-content/plugins/core/src/Assets/Admin/JS_Config.php
wp-content/plugins/core/src/Blocks/Block_Style_Deny_List.php
wp-content/plugins/core/src/Blocks/Block_Style_Override.php
wp-content/plugins/core/src/Blocks/Blocks_Definer.php
wp-content/plugins/core/src/Blocks/Blocks_Subscriber.php
wp-content/themes/core/assets/js/src/admin/config/wp-settings.js
wp-content/themes/core/assets/js/src/admin/core/block-styles.js

- Removes PHP based functionality for unregistering block styles
- Adds functionality for specifying blocks and their styles for unregistering
- Provides WP filter for it
- Unregisters specified blocks styles from JS
To remove specific core block styles from editor add the records to the `\Tribe\Project\Blocks\Blocks_Definer::DENY_BLOCK_STYLES` like this:
```php
self::DENY_BLOCK_STYLES => [
'core/separator' => [ 'default', 'wide', 'line', 'dots' ],
]
```
N/A

Feature: unregister block styles

---

changelog.md
composer.lock

- Brings in block generator updates to escape block labels: https://github.com/moderntribe/tribe-libs/pull/121

CHORE: Bump tribe libs to 3.4.18

---

changelog.md
wp-content/themes/core/components/card/js/card.js

Fixes an issue on Windows where right-clicks were incorrectly triggering link click-through.
This has been tested on an active project already. [Related Slack convo](https://tribe.slack.com/archives/C01CY7418GY/p1657046449714999)

Don't trigger click for mouse right-clicks on Windows.

---

changelog.md
wp-content/themes/core/components/blocks/buttons/buttons.php
wp-content/themes/core/components/blocks/buttons/css/buttons.pcss

This PR fixes up some a couple of issues causing the Buttons block to not get styled correctly:
1. Fixes individual button class name from being `b-links__list-link` to `b-buttons__button`.
2. Attaches appropriate action mixin to each button style type.
- [Link to Issue](https://moderntribe.atlassian.net/browse/SQONE-691)
- [Link to Demo](https://sq1-pr1015.moderntribe.qa/buttons-block-demo/)
- [Buttons Block Before](http://p.tri.be/nbSX6i)
- [Buttons Block After](http://p.tri.be/5Ckpyy)

[SQONE-691]: Buttons Block Updates

---

dev/docker/php/php-ini-overrides.ini

Improves container PHP performance. The default max accelerated files out of the box is `10000`, and a fresh square-one has `16388`.
Devs can run the following in their project to determine the amount of PHP files that exist, and adjust their project's default accordingly.
```bash
find . -type f -print | grep php | wc -l
```
I'd suggest you copy these into a (modern) project you're working on right now, do a `so stop; so start` and work as normal. Let us know in the comments if anything strange happens. I'm mostly curious for macOS users.
Specifically a bit concerned about this one on a mac: https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.file_update_protection
You can also dump https://www.php.net/manual/en/function.opcache-get-status.php to see some stats such.
Does …

Add optimized opcache configuration

---

changelog.md
wp-content/plugins/core/src/Admin/Admin_Subscriber.php
wp-content/plugins/core/src/Admin/Editor/Editor_Script_Loader.php
wp-content/themes/core/assets/js/src/admin/editor/tribe-tinymce.js

Fixes an issue where the TinyMCE floating/inline toolbar (usually when editing a link in the WYSIWYG) "flickers" endlessly. This is especially likely to happen when the TinyMCE editor is inside of a repeater (as in the Accordion block, for example) due the restricted horizontal space.
The issue is ticketed here: https://core.trac.wordpress.org/ticket/44911 and everyone pretty much agrees that it exists, but no one has fixed it in ~3 years.
The issue is caused by some poor positioning logic in `wp-includes/js/tinymce/plugins/wordpress/plugin.js`, which sometimes places the floating toolbar slightly off-screen when positioning it next to the inline element being edited. Overflowing the body this way causes horizontal scrollbars to appear and triggers a `scrollwindow` event. The same plugin …

[SQONE-708]: Fix for TinyMCE floating toolbar repositioning infinite loop.

---

changelog.md
dev/stubs/wordpress-overrides.stub
phpstan.neon.dist

- Properly tells PHPStan that the `have_posts()` function is impure
The following will no longer be tagged as `While loop condition is always true.` or `Unreachable statement - code above always terminates.`:
```php
<?php
if ( have_posts() ) : ?>
<div class="archive-loop__items g-3-up">
<?php while ( have_posts() ) :
the_post();
get_template_part( 'components/card/card', '', $c->get_extended_card_args(
$c->get_meta_primary(),
$c->get_meta_secondary()
) );
endwhile; ?>
</div>
<?php get_template_part( 'components/pagination/loop/loop' );
else :
get_template_part( 'components/no_results/no_results' );
endif;
?>
```

Bugfix: PHPStan have_posts() false positive

---

.lefthook/prepare-commit-msg/prefix-with-jira-ticket.php
changelog.md

* Fixed: Branches that have Jira projects in them that contained numbers in the name would not properly prefix git commits, e.g. `feature/DATA22-3/some-new-feature`
- Branches that contain a project with numbers will now prefix commit messages, e.g. if you commit `Updated card styles`, it would properly become `[DATA22-3]: Updated card styles`.
- Original style project names still work properly, e.g. `SQONE-689`.

Bugfix: Jira ticket prefixing numbered projects

---

changelog.md
wp-content/themes/core/components/share/Share_Controller.php

- Replaces `__()` with `esc_html__()` in `wp-content/themes/core/components/share/Share_Controller.php`
- Replaces Linkedin share URL with a new one

Fix: Share Linkedin URL

---

.lefthook/prepare-commit-msg/prefix-with-jira-ticket.php
changelog.md
dev/tests/tests/unit/PrefixJiraTicketTest.php
package.json
phpstan.neon.dist
yarn.lock

* Updated: Lefthook package renamed from @arkweid/lefthook to @evilmartians/lefthook. Updated to v1.1.1.
* Updated: `prefix-with-jira-ticket.php` lefthook script for better ticket matching and added tests.
After a `lefthook install -a`, commits to a branch with a ticket in it, e.g. `feature/JIRA-123/cool-thing` will continue to prefix the commit with the ticket, e.g. `[JIRA-123]: my commit message`.
[JIRA-123]: https://moderntribe.atlassian.net/browse/JIRA-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: Update lefthook ticket prefixing

---

changelog.md
wp-content/themes/core/components/tabs/Tabs_Controller.php

https://moderntribe.atlassian.net/browse/SQONE-609
- Fixes a regression that completely removed the type setting of a property in the Tabs Controller.
```
Whoops\Exception\ErrorException: Undefined array key &quot;tab_panel_classes&quot; in file /application/www/wp-content/plugins/core/src/Templates/Components/Abstract_Controller.php on line 39
Stack trace:
1. Whoops\Exception\ErrorException-&gt;() /application/www/wp-content/plugins/core/src/Templates/Components/Abstract_Controller.php:39
2. Whoops\Run-&gt;handleError() /application/www/wp-content/plugins/core/src/Templates/Components/Abstract_Controller.php:39
3. Tribe\Project\Templates\Components\Abstract_Controller-&gt;parse_args() /application/www/wp-content/themes/core/components/tabs/Tabs_Controller.php:70
4. …
```

[SQONE-609]: Fix regression in Tabs Controller

---

.gitignore
changelog.md

- Git ignore [lefthook-local.yml](https://github.com/evilmartians/lefthook/blob/master/docs/full_guide.md#local-config) as this version of SquareOne's PHPCS requires PHP 8.0+ locally, and will throw errors if that's not your default version. This allows developers to override the lefthook processing and point to a different PHP location if they need to.
- copy `lefthook.yml` to `lefthook-local.yml` and customize it.
- Lefthook will use the local version and it should be git ignored so it doesn't get committed.

Git ignore lefthook-local.yml

---

changelog.md
wp-content/themes/core/components/follow/Follow_Controller.php

- Using the Follow component would not output any social icons because the CSS class names were incorrect.
The icons now show up when using the Follow component:

Bugfix: Follow component social icon CSS class

---

changelog.md
wp-content/themes/core/components/blocks/links/css/links.pcss
wp-content/themes/core/integrations/gravity-forms/css/controls/consent.pcss
wp-content/themes/core/integrations/gravity-forms/index.pcss

Adds `pcss` support for the consent field that comes out of the box with GF.
(yes, I noticed I misspelled the branch name lol)

Add styles for the default consent field from Gravity Forms.

---

changelog.md
wp-content/themes/core/routes/single/Single_Controller.php

- Although WP Query says the `post_author` property is a string for compatibility reasons, functions using it expect it to be an integer.
I'm not sure why PHPSTAN allowed this through in the first place?

Bugfix: Single Controller `get_author_id()` now returns an integer type instead of a string.

---

changelog.md
wp-content/plugins/term-sorter/classes/Term_Sorter.php

- Adds a fix in the Term Sorter Plugin for the `wp_localize_script()` method: 3rd argument is expected to be an array, not a string
- Error is only seen locally when debug is on

Bugfix: Term Sorter

---

changelog.md
wp-content/plugins/core/src/Integrations/Yoast_SEO/Yoast_SEO_Subscriber.php

Removes `wpseo_json_ld_output` Yoast hook. This was removing the schema output.

Bugfix: Remove Yoast filter 

---

.deploy-ignore
.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml
.rsyncignore
changelog.md

- Add a single configuration file for all files/folders to ignore when using rsync to sync a built project's wp-content folder.
Any of these files inside of wp-content should never get deployed to a server.

Add .deploy-ignore file and update deploy workflows

---

changelog.md
wp-content/themes/core/components/blocks/content_loop/Content_Loop_Controller.php

Found this one out the hard way. It should be looking for an empty string. Surprised that [this is 5 months old](https://github.com/moderntribe/square-one/blame/ef0d180925a5dfef6d205b33c79157bcbf5330e0/wp-content/themes/core/components/blocks/content_loop/Content_Loop_Controller.php#L151).
Let's get this one merged before someone else get hit with it.

This check should be looking for an empty value.

---

changelog.md
wp-content/plugins/core/src/Nav_Menus/Walker/Walker_Nav_Menu_Primary.php

Without this patch, the primary nav menu outputs an invalid `aria-controls` attribute for primary menu dropdowns that looks like this:
```
<button 
title="Toggle Sub-Menu" id="menu-item-4"
class="c-nav-primary__action c-nav-primary__action--depth-0 c-nav-primary__action--has-children"
data-js="c-nav-child-menu-trigger"
aria-expanded="true"
aria-haspopup="true"
aria-controls="menu-item-child-4&quot;"
>
About Us
</button>
```
Note the trailing escaped `&quot;` character in the `aria-controls` attribute, which makes this an invalid ARIA attribute for controlling the `#menu-item-child-4` dropdown.
- https://moderntribe.atlassian.net/browse/SQONE-718

SQONE-718: Remove extraneous quote in primary nav walker

---

changelog.md
wp-content/themes/core/assets/js/src/admin/editor/tribe-tinymce.js

This patch fixes an edge case where there are multiple TinyMCE editors active on a given page (imagine _Appearance → Theme Configuration_ with multiple tabs, several of which have a WYSIWYG field, for example). Without this patch, the `tribe-tinymce` plugin (which itself fixes a different core Wordpress + TinyMCE bug) fails to find the correct editor and breaks TinyMCE floating toolbar positioning (they end up positioned offscreen and unusable).
- https://moderntribe.atlassian.net/browse/SQONE-719

Fix for multiple TinyMCE editors on the same page

---

.github/workflows/ci.yml

- `ci.yml` wasn't actually using the correct PHP version due to a typo.

Fix php version typo
